apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: diksha1159/hello-world-app:latest
          ports:
            - containerPort: 3000
